os: osx
language: generic
sudo: required
osx_image: xcode9.4
before_install:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - .travis/update-submodule.sh
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - brew install vapor/tap/vapor
  - swift build
  - swift test
env:
  global:
    - CC_TEST_REPORTER_ID=6133dfb857104f811740c22973bcb412866eba231509f7f8f60a8ad95005ee2b
    - secure: ZubW/TIAZCjYPJYI1mwUtWhY9iAabIQzyeexKGEbcbUuYhdCzZ2Dj7mIjPyOQ0KPwQm3nwWPRXq8V7YnGJMU3ytofu/PTb0gYDGPguVpLj0k7hN3xlxuODQeP2BtiS4uzuXspMfOb14kEkszFqU0qlF/eKnKBtqvva//Iwi2L3I=
